services:
  - type: web
    name: tikets-ruben
    env: python
    region: oregon
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 240"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
